# Generated by Django 5.0.7 on 2024-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
    ]
