# Generated by Django 5.0.7 on 2024-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_alter_buyproduct_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
