# Generated by Django 5.0.7 on 2024-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='product_qty',
            field=models.IntegerField(default=1),
        ),
    ]
