# Generated by Django 5.0.7 on 2024-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_favourite_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra pradesh'), ('Karnataga', 'karnataga'), ('Tamilnadu', 'Tamilnadu'), ('Kerala', 'Kerala')], max_length=200),
        ),
    ]
